// <auto-generated />
using Blazor_CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor_CRUD.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Blazor_CRUD.Data.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This is some exemple for post 1. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "This is some exemple for post 2. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This is some exemple for post 3. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "This is some exemple for post 4. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "This is some exemple for post 5. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "This is some exemple for post 6. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 6"
                        },
                        new
                        {
                            Id = 7,
                            Content = "This is some exemple for post 7. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 7"
                        },
                        new
                        {
                            Id = 8,
                            Content = "This is some exemple for post 8. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 8"
                        },
                        new
                        {
                            Id = 9,
                            Content = "This is some exemple for post 9. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 9"
                        },
                        new
                        {
                            Id = 10,
                            Content = "This is some exemple for post 10. The content is very interstring and I just wanded it to be two sentences to long.",
                            Title = "Post 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
